apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - seaweedfs.yaml
  - seaweedfs-bucket-job.yaml
  - objectstore.yaml
  - cluster.yaml
  - pooler.yaml
  - backup.yaml
  - pgadmin.yaml
  - monitoring/dashboards.yaml
  - monitoring/podmonitor.yaml
